#!/bin/bash
echo "GitHub username:"
read github_user

echo "GitHub repository name:"
read github_repo

echo "Maintainer full name:"
read maintainer

echo "Library name (without spaces. E.g. base-library):"
read lib_name

echo "Library description:"
read lib_description

echo "Library package (e.g. net.gotev.baselibrary):"
read lib_package_name

echo "Library project group (e.g. net.gotev):"
read lib_project_group

echo "Demo App package (e.g. net.gotev.baselibrarydemo):"
read demoapp_package_name

function rename {
    echo "renaming $1 to $2"
    grep -rl "$1" . --exclude-dir=.gradle --exclude-dir=build --exclude-dir=.git | grep -v "./rename" | xargs sed -i '' -e "s/$1/$2/g"
}

rename "GITHUB_USER" "${github_user}"
rename "GITHUB_REPOSITORY_NAME" "${github_repo}"
rename "MAINTAINER_FULL_NAME" "${maintainer}"
rename "LIBRARY_DESCRIPTION" "${lib_description}"
rename "net.gotev.baselibrary" "${lib_package_name}"
rename "LIBRARY_PROJECT_GROUP" "${lib_project_group}"
rename "net.gotev.baselibrarydemo" "${demoapp_package_name}"

LIB_PACKAGE_DIRECTORIES="${lib_package_name//\.//}"
DEMOAPP_PACKAGE_DIRECTORIES="${demoapp_package_name//\.//}"
CURDIR=$(pwd)

function move_package {
    mkdir -p "$2"
    mv -v "${1}/"* "${2}/"
    ROOT_DIR=$(echo "$1" | tr "/" "\n" | head -n 1)
    rm -rf "$ROOT_DIR"
}

cd "$CURDIR"
cd library/src/main/java/
move_package "net/gotev/baselibrary" "$LIB_PACKAGE_DIRECTORIES"

cd "$CURDIR"
cd library/src/test/java/
move_package "net/gotev/baselibrary" "$LIB_PACKAGE_DIRECTORIES"

cd "$CURDIR"
cd library/src/androidTest/java/
move_package "net/gotev/baselibrary" "$LIB_PACKAGE_DIRECTORIES"

cd "$CURDIR"
mv -v library "${lib_name}"
rename ":library" ":${lib_name}"
rename "../library" "../${lib_name}"

cd "$CURDIR"
cd example/app/src/main/java/
move_package "net/gotev/baselibrarydemo" "$DEMOAPP_PACKAGE_DIRECTORIES"

cd "$CURDIR"
cd example/app/src/test/java/
move_package "net/gotev/baselibrarydemo" "$DEMOAPP_PACKAGE_DIRECTORIES"

cd "$CURDIR"
cd example/app/src/androidTest/java/
move_package "net/gotev/baselibrarydemo" "$DEMOAPP_PACKAGE_DIRECTORIES"
